<?php

//Invalid Test Cases Below

/**
 * There are Tabs Below.
 */
		$string = "Hello Test";

/**
 * There are trailing spaces below. At the end of the line
 * and the the first character of the following line.
 */
$string = "Hello Spaces";   
 

/**
 * 
 */
 function testing_function() { // Function is off one space it should start the the gutter.
   $three = 'Contain Three Spaces';
   
  if (TRUE) {
      $test = 'Off an extra Tab';
     $test2 = 'Off an extra Space';
  }
}
 
/**
 * This is the end of the File. It does not contain a New Line (\n) at the end
 */